import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {PokeCard} from "@/components/UI/PokeCard/PokeCard";
import {Navbar} from "@/components/UI/Navbar/Navbar";
import {PokemonsList} from "@/components/UI/PokemonsList";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>
            <main className="m-10">
                <PokemonsList />
            </main>
        </>
    )
}
